services:
  redis:
    container_name: backend_cyl_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - backend_cyl_network

volumes:
  redis_data:
    driver: local

networks:
  backend_cyl_network:
    driver: bridge
