services:
  app:
    container_name: app_backend_cyl
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME:-RAG_system}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-0000}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: ${REDIS_DB:-0}
      ES_HOST: http://es:9200
      ES_HOSTS: http://es:9200
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      es:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_rag_network

  mysql:
    container_name: backend_cyl_mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-0000}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME:-RAG_system}
      TZ: ${TIMEZONE:-Asia/Shanghai}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks:
      - backend_rag_network

  redis:
    container_name: backend_cyl_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - backend_rag_network
  
  es:
    container_name: es_01
    image: elasticsearch:9.4.1
    volumes:
      - es_knowledge_data_01:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins
      - ./docker_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    env_file: .env
    environment:
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - bootstrap.memory_lock=false
      - TZ=${TIMEZONE}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    restart: on-failure
    networks:
      - backend_rag_network
  
  kibana:
    container_name: kibana_cyl
    image: kibana:9.4.1
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./docker_conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    restart: on-failure
    networks:
      - backend_rag_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  es_knowledge_data_01:
    driver: local
  es_plugins:
    driver: local
  kibana_data:
    driver: local
  

networks:
  backend_rag_network:
    driver: bridge
